spring:
  application:
    name: spring-crud-generator-demo

  datasource:
    url: jdbc:posgresql://localhost:5432/spring-crud-generator-demo
    username: app
    password: app

  flyway:
    enabled: true
    baseline-on-migrate: false

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10s
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
    show-sql: true
    open-in-view: false

  graphql:
    schema:
      locations:
       - classpath:graphql