spring:
  application:
    name: spring-crud-generator-demo

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:posgresql://localhost:5432/spring-crud-generator-demo}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}

  flyway:
    enabled: true
    baseline-on-migrate: false

  cache:
    type: redis

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 10s
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
    show-sql: true
    open-in-view: false

  graphql:
    schema:
      locations:
       - classpath:graphql